### ISSUE TITLE
Add ScientificTypes for text analysis

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/ScientificTypesBase.jl#12]
**Discussion starter**

A Slacker is volunteering to add some text-based analysis transformers to MLJ. This requires some decisions here, to support.

Recall here that a *scitype* is a julia type used to articulate an algorithm's type requirements in a "machine representation" agnostic way.  See the readme of this pkg and [ScientificTypes.jl](https://github.com/JuliaAI/ScientificTypes.jl) for more detail.

At the moment we have a single type `Textual`. The convention in ScientificTypes.jl is `scitype(x) = Textual` iff `x isa AbstractString`.

For text analysis I guess we need a new type `Document` which wraps some text in metadata (title, author, and so forth). Generally, we do not have separate scitypes for different "scientifically equivalent" representations of data. For example, all Tables.jl compatible tables have `Table{K}` as their scitype in the standard convention. So, in the same way, different document representations, eg, `StringDocument`, `FileDocument`, `TokenDocument`, `NGramDocument` from TextAnalysis.jl - could be declared to have `Document` scitype in the standard convention (`scitype(::AbstractDocument) = Document`).  Algorithms working on documents can dispatch on the specific representation, yes? 

It seems clear that it does not make sense for `Document` (wrapped text) to be a subtype of `Textual` (plain text) no more than matrices are viewed as tables. Do they need a common supertype?  If so, goodness knows what to call it.  Ideally, we should rename `Textual` as `PlainText` and make `Textual` the supertype?? This probably wouldn't break too much but we shouldn't do it unless there is a perceived need. It's probably fine to just use `Union` types if really necessary. 

As far as I can tell, `Corpus` in TextAnalysis is essentially just a list of documents and does not really wrap the list in metadata. Is this true? If so, I don't think we need a `Corpus` scitype, as `AbstractVector{Document}` ought to do. We could declare `scitype(::Corpus) = AbstractVector{Document}` (while we would get `scitype(::AbstractVector{<:AbstractDocument}) = AbstractVector{Document}` automatically from scitype rules about arrays). And an algorithm needing `Corpus` type but given some vector of documents could first wrap them as a `Corpus`, yes?

cc @pazzo83
cc @aviks @oxinabox @giordano @dellison

**Comment by ablaom** [comment]
cc @pazzo83

**Comment by oxinabox** [comment]
For interest
[CorpusLoaders.jl](https://github.com/JuliaText/CorpusLoaders.jl/blob/master/src/types.jl) takes the position that textual data is represented as some nested iterator.
Where each level of the iterator might have annotations (but most commonly those are at the word level where they are e.g. NER or POS tagged etc).
It is used with [MultiResolutionIterators.jl](https://github.com/oxinabox/MultiResolutionIterators.jl) which manipulates such things.
Different NLP tasks need different data and treat them differently; see the readme for MultiResolutionIterators.
I am not sure if there is much of interest one can do with a SciType for it.

**Comment by pazzo83** [comment]
Thanks for setting this up!  I agree about the `Document` type.  I was able to get the TF-IDF transformer I wrote to work inside of an MLJ pipeline by passing in the vector of `Document`s from the corpus, so having a type for Corpus doesn't seem necessary.  In fact, I have a method defined that just takes in a vector of `Document`s and creates a Corpus inside the transformer just to add some flexibility.

**Comment by ablaom** [comment]
@oxinabox Thanks for pointing out MultiResolutionIterators.jl. That's a very nice design. 

Yes, I can see that NLP is probably moving in multiple directions with little enough in common to easily fit into a ScientificType framework with consensus about conventions. 

Still, there is a need for *something* as @pazzo83 's use case demonstrates. I think we could have a stab at a type or types that keep the extra generality hinted at MultiResolutionIterators in mind, and consider the specific `scitype` *convention* we adopt as a pragmatic experiment. 

How about two atomic types `Textual` (which currently means `AbstractString`) and `Character` and a new type `AnnotatedArray{T,N}` for array-like collections that also include metadata. In this language, a "document"  the sense of TextAnalysis  (some string wrapped in metadata ) is something with scitype `AnnotatedArray{Textual, 1}`. If additionally sentences are to be considered individual units, but are not annotated, then we have an element of `AnnotatedArray{AbstractArray{Textual, 1}, 1}` and so forth. 

Advantage over previous suggestion: More flexible
Disadvantage: More head-scratching for users

Thoughts anyone?

**Comment by ablaom** [comment]
cc @fkiraly

**Comment by ablaom** [comment]
Mmm. One problem with using TextAnalysis types in any scitype convention is that this is rather a large package, which we would need to add to the dependencies of ScientificTypes. 

```julia
julia> @time using ScientificTypes
  1.116427 seconds (1.60 M allocations: 114.576 MiB)

julia> @time using TextAnalysis
  2.280023 seconds (3.90 M allocations: 218.939 MiB, 2.71% gc time)
```

@aviks What's the likelihood of TextAnalysis moving it's basic types into a base package, in the near future?

**Comment by fkiraly** [comment]
>cc @fkiraly

Thou hast summon'd me, what dost thou bidde?

> `scitype(x) = Textual` iff `x isa AbstractString`

Generally, I think this makes sense, but I think it is worth being careful with two things:

* distinction between "root types" like document, text, and "feature types" like n-grams, tokens, etc. For instance, an n-gram I'd think is a `Tuple(AbstractString)`, so an n-gram document would be a `Multiset(Ngram)`, so a `Multiset(Tuple(AbstractString))`? I.e., some special case of `FeatureScitypeBasedOn(Textual)` rather than a "subtype" of `Textual`.
* distinction between annotations being intrinsic vs being intrinsic. E.g., is an annotated document an `Annotated(Document)`, or a pair of `Document` and `AnnotationOf(Document)`? An algorithm that (after some training) annotates documents would have scitype `Supervised(Document -> AnnotationOf(Document)` rather than `Supervised(Document -> Annotated(Document)`, no? Similar to how in time series segmentation, I'd think of the segmenter as `Supervised(TimeSeries -> SegmentationOf(TimeSeries)`.

**Comment by ablaom** [comment]
@storopoli Appreciate the input. To clarify, `Textual` is an existing type and, in the standard convention any `AbstractString` has this scitype (and nothing else does). The issue here is how to extend scitypes to text "containers", which might include metadata, and whose structure could be nested.
