### ISSUE TITLE
Reorganization of scitypes in source code

### ISSUE THREAD

**Issue by juliohm** [JuliaAI/ScientificTypesBase.jl#21]
After #20 is reviewed, can I help reorganizing the types in the source code? I find the scitype section a bit confusing to read. I would like to struct it as a tree of types so that readers can follow the type hierarchy more easily. Also, I could take this opportunity to deprecate some old types like Scientific from the source.

Please let me know if that would be helpful. I plan to work more closely with ScientificTypes.jl moving forward as well.

cc: @ablaom

**Comment by ablaom** [comment]
Thanks for the offer to help out. 

> can I help reorganizing the types in the source code?

@OkonSamuel is this likely to cause merge conflict pain with the PR's you are working on?

To be honest, more helpful would be to [improve the organization](https://github.com/JuliaAI/ScientificTypes.jl/issues/163) of /test at ScientificTypes, but that's not going to be much fun 😉

**Comment by juliohm** [comment]
@OkonSamuel please let me know if I can cleanup the house in the main source file. The plan is to just move things around in a first PR, and then reassess the code.

**Comment by OkonSamuel** [comment]
> @OkonSamuel please let me know if I can cleanup the house in the main source file. The plan is to just move things around in a first PR, and then reassess the code.

I'll open a PR this weekend so we can discuss and move things around. Am currently working on improving performance.

**Comment by juliohm** [comment]
Hi @OkonSamuel , any update on this issue? I am working actively in a project where scientific types will be first-class and would like to contribute to this code more actively. Please let me know when I can start working on a PR.
